### ISSUE TITLE
Use purs-tidy to format

### ISSUE THREAD

**Issue by yukikurage** [sigma-andex/purescript-fast-vect#18]
https://www.npmjs.com/package/@rowtype-yoga/prettier-plugin-purescript
is now deprecated.
ref: https://github.com/rowtype-yoga/pose

Since purs-tidy is becoming the de facto standard, it is better to use that. It has a unicode setting, so we can make it match the original formatting of this package.

**Comment by yukikurage** [comment]
We could consider changing the formatting method.
If you like Unicode, we can leave it as it is, but looking at your other repositories, it seems you don't use Unicode....

**Comment by sigma-andex** [comment]
Yeah the pose predates tidy. We can switch to tidy, no problem
