### ISSUE TITLE
Should `Vect` have a `EuclideanRing` instance?

### ISSUE THREAD

**Issue by pete-murphy** [sigma-andex/purescript-fast-vect#29]
It seems like this instance would be lawful, from what I understand
```purs
instance (Compare len Common.NegOne GT, Reflectable len Int, EuclideanRing a) => EuclideanRing (Vect len a) where
  div = lift2 div
  mod = lift2 mod
  degree = const 1
```
The thing I'm most uncertain about is the `degree` implementation, I don't really understand what `degree` is and why it's part of `EuclideanRing`, but here's what the [docs for `EuclideanRing`](https://github.com/purescript/purescript-prelude/blob/f4cad0ae8106185c9ab407f43cf9abf05c256af4/src/Data/EuclideanRing.purs#L44C1-L47C15) say:
> For any `EuclideanRing` which is also a `Field`, one valid choice for `degree` is simply `const 1`. In fact, unless there's a specific reason not to, `Field` types should normally use this definition of `degree`.

**Comment by artemisSystem** [comment]
that looks good to me on a first glance

**Comment by sigma-andex** [comment]
Feel free to create a PR
